// <auto-generated />
using System;
using CartFlow.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartFlow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630202731_product_seed_created")]
    partial class product_seed_created
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartFlow.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("CartFlow.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("CartFlow.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ColorIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IconIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("CartFlow.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .IsUnique()
                        .HasFilter("[CartId] IS NOT NULL");

                    b.ToTable("Coupons", (string)null);
                });

            modelBuilder.Entity("CartFlow.Models.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Discounts", (string)null);
                });

            modelBuilder.Entity("CartFlow.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f292b22-24dd-4950-96ab-9e9c13ffe46f"),
                            CategoryId = new Guid("019f08a6-792e-716c-aa96-a77a670b615a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teknoloji kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Teknoloji Ürünü 1",
                            Price = 137m,
                            Sold = 7,
                            Stock = 23
                        },
                        new
                        {
                            Id = new Guid("36eeeebe-eb18-4e26-83db-f09ceadcb990"),
                            CategoryId = new Guid("019f08a6-792e-716c-aa96-a77a670b615a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teknoloji kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Teknoloji Ürünü 2",
                            Price = 274m,
                            Sold = 14,
                            Stock = 26
                        },
                        new
                        {
                            Id = new Guid("a4727782-2a4b-49d3-93c7-4202b1a4b6a9"),
                            CategoryId = new Guid("019f08a6-792e-716c-aa96-a77a670b615a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teknoloji kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Teknoloji Ürünü 3",
                            Price = 411m,
                            Sold = 21,
                            Stock = 29
                        },
                        new
                        {
                            Id = new Guid("c95c3c9e-e5a7-4306-b5e7-7eec3144327d"),
                            CategoryId = new Guid("019f08a6-792e-716c-aa96-a77a670b615a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teknoloji kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Teknoloji Ürünü 4",
                            Price = 548m,
                            Sold = 28,
                            Stock = 32
                        },
                        new
                        {
                            Id = new Guid("466ef3c0-c2d9-4198-9f18-f272aaee8631"),
                            CategoryId = new Guid("019f08a6-792e-716c-aa96-a77a670b615a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teknoloji kategorisi örnek ürün 5",
                            IsActive = true,
                            Name = "Teknoloji Ürünü 5",
                            Price = 685m,
                            Sold = 35,
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("9ac8d55c-d87e-4b46-80c1-4ca3900c9351"),
                            CategoryId = new Guid("019f08a6-792e-716c-aa96-a77a670b615a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teknoloji kategorisi örnek ürün 6",
                            IsActive = true,
                            Name = "Teknoloji Ürünü 6",
                            Price = 822m,
                            Sold = 42,
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("2b068a3a-4625-4a86-8edf-1c178bf948aa"),
                            CategoryId = new Guid("019f08b8-f30b-7ed0-a389-087547932d37"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gayrimenkul kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Gayrimenkul Ürünü 1",
                            Price = 359m,
                            Sold = 49,
                            Stock = 41
                        },
                        new
                        {
                            Id = new Guid("a41a23aa-b996-45ee-b8b3-71d39a571e59"),
                            CategoryId = new Guid("019f08b8-f30b-7ed0-a389-087547932d37"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gayrimenkul kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Gayrimenkul Ürünü 2",
                            Price = 496m,
                            Sold = 56,
                            Stock = 44
                        },
                        new
                        {
                            Id = new Guid("a86df4b5-0b5b-41e5-8845-1dd5d12fba76"),
                            CategoryId = new Guid("019f08b8-f30b-7ed0-a389-087547932d37"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gayrimenkul kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Gayrimenkul Ürünü 3",
                            Price = 633m,
                            Sold = 63,
                            Stock = 47
                        },
                        new
                        {
                            Id = new Guid("13351535-9a3c-492b-9b85-6bad6241bf0c"),
                            CategoryId = new Guid("019f08b8-f30b-7ed0-a389-087547932d37"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gayrimenkul kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Gayrimenkul Ürünü 4",
                            Price = 770m,
                            Sold = 70,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("f07149b9-ab05-45ce-b960-b1c0d84289e8"),
                            CategoryId = new Guid("019f08b9-29a2-714a-a6f2-1d4a0734e73d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aksesuar kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Aksesuar Ürünü 1",
                            Price = 507m,
                            Sold = 77,
                            Stock = 53
                        },
                        new
                        {
                            Id = new Guid("627fe19c-5969-4e47-8f0a-ca0d69c6cf71"),
                            CategoryId = new Guid("019f08b9-29a2-714a-a6f2-1d4a0734e73d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aksesuar kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Aksesuar Ürünü 2",
                            Price = 644m,
                            Sold = 84,
                            Stock = 56
                        },
                        new
                        {
                            Id = new Guid("20965ea0-ce83-470e-9638-2674ca3299da"),
                            CategoryId = new Guid("019f08b9-29a2-714a-a6f2-1d4a0734e73d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aksesuar kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Aksesuar Ürünü 3",
                            Price = 781m,
                            Sold = 1,
                            Stock = 59
                        },
                        new
                        {
                            Id = new Guid("12434a5c-3d58-41a4-8985-4f7e09ff8a9c"),
                            CategoryId = new Guid("019f08b9-29a2-714a-a6f2-1d4a0734e73d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aksesuar kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Aksesuar Ürünü 4",
                            Price = 918m,
                            Sold = 8,
                            Stock = 62
                        },
                        new
                        {
                            Id = new Guid("3c473a3c-fe57-41bd-bb1b-cfa749207ffb"),
                            CategoryId = new Guid("019f08b9-29a2-714a-a6f2-1d4a0734e73d"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aksesuar kategorisi örnek ürün 5",
                            IsActive = true,
                            Name = "Aksesuar Ürünü 5",
                            Price = 1055m,
                            Sold = 15,
                            Stock = 65
                        },
                        new
                        {
                            Id = new Guid("de1ad4eb-a460-48b3-bf66-96212dbeaf26"),
                            CategoryId = new Guid("019f08ba-5838-7d1f-8298-2921c18d770c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spor kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Spor Ürünü 1",
                            Price = 692m,
                            Sold = 22,
                            Stock = 68
                        },
                        new
                        {
                            Id = new Guid("c340637c-4891-4ec5-9639-4b694e065319"),
                            CategoryId = new Guid("019f08ba-5838-7d1f-8298-2921c18d770c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spor kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Spor Ürünü 2",
                            Price = 829m,
                            Sold = 29,
                            Stock = 71
                        },
                        new
                        {
                            Id = new Guid("5914b56f-7705-4bbb-a853-3b82fd4c9ff4"),
                            CategoryId = new Guid("019f08ba-5838-7d1f-8298-2921c18d770c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spor kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Spor Ürünü 3",
                            Price = 966m,
                            Sold = 36,
                            Stock = 74
                        },
                        new
                        {
                            Id = new Guid("de134ad5-da0f-48ac-8e55-bcf801770f4b"),
                            CategoryId = new Guid("019f08ba-5838-7d1f-8298-2921c18d770c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spor kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Spor Ürünü 4",
                            Price = 1103m,
                            Sold = 43,
                            Stock = 77
                        },
                        new
                        {
                            Id = new Guid("14fdb833-77f2-493b-b20c-b2fbb7a67254"),
                            CategoryId = new Guid("019f08ba-5838-7d1f-8298-2921c18d770c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spor kategorisi örnek ürün 5",
                            IsActive = true,
                            Name = "Spor Ürünü 5",
                            Price = 1240m,
                            Sold = 50,
                            Stock = 80
                        },
                        new
                        {
                            Id = new Guid("1324f2ea-5a60-4ca2-bd96-3dbec3e66d45"),
                            CategoryId = new Guid("019f08ba-8a2f-7489-b10e-de71178d9a20"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giyim kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Giyim Ürünü 1",
                            Price = 877m,
                            Sold = 57,
                            Stock = 83
                        },
                        new
                        {
                            Id = new Guid("fc496a28-e985-4193-b1e8-9face21d32a6"),
                            CategoryId = new Guid("019f08ba-8a2f-7489-b10e-de71178d9a20"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giyim kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Giyim Ürünü 2",
                            Price = 1014m,
                            Sold = 64,
                            Stock = 86
                        },
                        new
                        {
                            Id = new Guid("40f6cbfe-66cb-43e1-85ee-8c853f655891"),
                            CategoryId = new Guid("019f08ba-8a2f-7489-b10e-de71178d9a20"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giyim kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Giyim Ürünü 3",
                            Price = 1151m,
                            Sold = 71,
                            Stock = 89
                        },
                        new
                        {
                            Id = new Guid("dd795d21-3775-43a3-b431-cf23fd1bd2ae"),
                            CategoryId = new Guid("019f08ba-8a2f-7489-b10e-de71178d9a20"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giyim kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Giyim Ürünü 4",
                            Price = 1288m,
                            Sold = 78,
                            Stock = 92
                        },
                        new
                        {
                            Id = new Guid("7ce65e2a-5d85-46d9-8f9e-3d4f285386b8"),
                            CategoryId = new Guid("019f08ba-8a2f-7489-b10e-de71178d9a20"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giyim kategorisi örnek ürün 5",
                            IsActive = true,
                            Name = "Giyim Ürünü 5",
                            Price = 1425m,
                            Sold = 85,
                            Stock = 95
                        },
                        new
                        {
                            Id = new Guid("0261e398-0648-4587-af80-cd76832f9324"),
                            CategoryId = new Guid("019f08ba-b96f-73af-bed7-201a139d6f66"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kitap kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Kitap Ürünü 1",
                            Price = 1062m,
                            Sold = 2,
                            Stock = 98
                        },
                        new
                        {
                            Id = new Guid("dcaee9df-1af7-4a53-9467-55546f4ddcbf"),
                            CategoryId = new Guid("019f08ba-b96f-73af-bed7-201a139d6f66"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kitap kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Kitap Ürünü 2",
                            Price = 1199m,
                            Sold = 9,
                            Stock = 101
                        },
                        new
                        {
                            Id = new Guid("6f9066aa-518a-433a-85f2-745dec20299a"),
                            CategoryId = new Guid("019f08ba-b96f-73af-bed7-201a139d6f66"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kitap kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Kitap Ürünü 3",
                            Price = 1336m,
                            Sold = 16,
                            Stock = 104
                        },
                        new
                        {
                            Id = new Guid("11feb522-b6e5-4925-b3e0-8227e61c97e3"),
                            CategoryId = new Guid("019f08ba-b96f-73af-bed7-201a139d6f66"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kitap kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Kitap Ürünü 4",
                            Price = 1473m,
                            Sold = 23,
                            Stock = 107
                        },
                        new
                        {
                            Id = new Guid("c59a61cc-38a8-4509-b52e-d214b6bd82a0"),
                            CategoryId = new Guid("019f08ba-b96f-73af-bed7-201a139d6f66"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kitap kategorisi örnek ürün 5",
                            IsActive = true,
                            Name = "Kitap Ürünü 5",
                            Price = 1610m,
                            Sold = 30,
                            Stock = 110
                        },
                        new
                        {
                            Id = new Guid("c33c4990-3106-4dfb-8ae3-6fe1bbf62cb3"),
                            CategoryId = new Guid("019f08ba-efa5-787a-ab95-48dc207f7884"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oyun kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Oyun Ürünü 1",
                            Price = 1247m,
                            Sold = 37,
                            Stock = 113
                        },
                        new
                        {
                            Id = new Guid("1793b925-64b5-4861-93f2-3966b2c4ad60"),
                            CategoryId = new Guid("019f08ba-efa5-787a-ab95-48dc207f7884"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oyun kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Oyun Ürünü 2",
                            Price = 1384m,
                            Sold = 44,
                            Stock = 116
                        },
                        new
                        {
                            Id = new Guid("a38d379c-b943-446e-9995-dc733e820ce2"),
                            CategoryId = new Guid("019f08ba-efa5-787a-ab95-48dc207f7884"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oyun kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Oyun Ürünü 3",
                            Price = 1521m,
                            Sold = 51,
                            Stock = 119
                        },
                        new
                        {
                            Id = new Guid("e11f6d49-4e30-45ba-b79e-278c5a0e697d"),
                            CategoryId = new Guid("019f08ba-efa5-787a-ab95-48dc207f7884"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oyun kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Oyun Ürünü 4",
                            Price = 1658m,
                            Sold = 58,
                            Stock = 122
                        },
                        new
                        {
                            Id = new Guid("a0781b94-9419-4ae0-a5cc-7f2cee2ec837"),
                            CategoryId = new Guid("019f08ba-efa5-787a-ab95-48dc207f7884"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oyun kategorisi örnek ürün 5",
                            IsActive = true,
                            Name = "Oyun Ürünü 5",
                            Price = 1795m,
                            Sold = 65,
                            Stock = 125
                        },
                        new
                        {
                            Id = new Guid("88ae29a7-a070-4cb8-9dfe-ddab20bb3b68"),
                            CategoryId = new Guid("019f08bb-1a94-76c5-9a80-049bb0539f35"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gıda kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Gıda Ürünü 1",
                            Price = 1432m,
                            Sold = 72,
                            Stock = 128
                        },
                        new
                        {
                            Id = new Guid("0cf83315-057b-4491-9ae4-d9180dc2a16b"),
                            CategoryId = new Guid("019f08bb-1a94-76c5-9a80-049bb0539f35"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gıda kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Gıda Ürünü 2",
                            Price = 1569m,
                            Sold = 79,
                            Stock = 131
                        },
                        new
                        {
                            Id = new Guid("047a442a-0d7a-4942-9400-6fbdfde190e6"),
                            CategoryId = new Guid("019f08bb-1a94-76c5-9a80-049bb0539f35"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gıda kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Gıda Ürünü 3",
                            Price = 1706m,
                            Sold = 86,
                            Stock = 134
                        },
                        new
                        {
                            Id = new Guid("32c4cb38-ef1c-489c-bcf8-7fa70b9d5b3a"),
                            CategoryId = new Guid("019f08bb-1a94-76c5-9a80-049bb0539f35"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gıda kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Gıda Ürünü 4",
                            Price = 1843m,
                            Sold = 3,
                            Stock = 137
                        },
                        new
                        {
                            Id = new Guid("ae4a3e70-3dd5-428f-882d-0138aa2bec07"),
                            CategoryId = new Guid("019f08bb-6b1f-7605-b8a0-c2c887cf4699"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bahçe kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Bahçe Ürünü 1",
                            Price = 1580m,
                            Sold = 10,
                            Stock = 140
                        },
                        new
                        {
                            Id = new Guid("0d5027f5-2b74-44f6-9283-7433b3dcf1b1"),
                            CategoryId = new Guid("019f08bb-6b1f-7605-b8a0-c2c887cf4699"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bahçe kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Bahçe Ürünü 2",
                            Price = 1717m,
                            Sold = 17,
                            Stock = 143
                        },
                        new
                        {
                            Id = new Guid("e34af255-11f5-4ba7-8ae7-6cfedb6f5762"),
                            CategoryId = new Guid("019f08bb-6b1f-7605-b8a0-c2c887cf4699"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bahçe kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Bahçe Ürünü 3",
                            Price = 1854m,
                            Sold = 24,
                            Stock = 146
                        },
                        new
                        {
                            Id = new Guid("2c0004ee-c113-4678-9a0b-3bb33e25b215"),
                            CategoryId = new Guid("019f08bb-6b1f-7605-b8a0-c2c887cf4699"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bahçe kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Bahçe Ürünü 4",
                            Price = 1991m,
                            Sold = 31,
                            Stock = 149
                        },
                        new
                        {
                            Id = new Guid("ebe56a59-4a80-494e-943d-c1141d3fc04c"),
                            CategoryId = new Guid("019f08bb-9b46-7db5-91c5-bcb874f42aff"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sanat kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Sanat Ürünü 1",
                            Price = 1728m,
                            Sold = 38,
                            Stock = 152
                        },
                        new
                        {
                            Id = new Guid("e90ef6b0-a66a-41aa-a2ea-4475f94239ad"),
                            CategoryId = new Guid("019f08bb-9b46-7db5-91c5-bcb874f42aff"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sanat kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Sanat Ürünü 2",
                            Price = 1865m,
                            Sold = 45,
                            Stock = 155
                        },
                        new
                        {
                            Id = new Guid("d28254cc-56bc-47bd-864d-0e178830b7b6"),
                            CategoryId = new Guid("019f08bb-9b46-7db5-91c5-bcb874f42aff"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sanat kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Sanat Ürünü 3",
                            Price = 2002m,
                            Sold = 52,
                            Stock = 158
                        },
                        new
                        {
                            Id = new Guid("fbe8c1bd-552b-453c-8da1-27a445725977"),
                            CategoryId = new Guid("019f08bb-9b46-7db5-91c5-bcb874f42aff"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sanat kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Sanat Ürünü 4",
                            Price = 2139m,
                            Sold = 59,
                            Stock = 161
                        },
                        new
                        {
                            Id = new Guid("4b549ee9-6bfb-48ef-8a7b-9c93f6263ccb"),
                            CategoryId = new Guid("019f08bb-d442-7fb7-a6cf-5325fb2b51f1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Alet kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Alet Ürünü 1",
                            Price = 1876m,
                            Sold = 66,
                            Stock = 164
                        },
                        new
                        {
                            Id = new Guid("ed3ebdb5-0db9-4a36-899d-bf6e86679fa4"),
                            CategoryId = new Guid("019f08bb-d442-7fb7-a6cf-5325fb2b51f1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Alet kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Alet Ürünü 2",
                            Price = 2013m,
                            Sold = 73,
                            Stock = 167
                        },
                        new
                        {
                            Id = new Guid("71336fa8-4118-4e08-b2c7-a7a5dd0f3da5"),
                            CategoryId = new Guid("019f08bb-d442-7fb7-a6cf-5325fb2b51f1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Alet kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Alet Ürünü 3",
                            Price = 2150m,
                            Sold = 80,
                            Stock = 170
                        },
                        new
                        {
                            Id = new Guid("234db44a-993b-4cd8-89ee-9ae92cc392aa"),
                            CategoryId = new Guid("019f08bb-d442-7fb7-a6cf-5325fb2b51f1"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Alet kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Alet Ürünü 4",
                            Price = 2287m,
                            Sold = 87,
                            Stock = 173
                        },
                        new
                        {
                            Id = new Guid("24ec1441-8f30-4fbc-bc0a-8e273c3ad8b4"),
                            CategoryId = new Guid("019f08bc-1283-75a5-a94f-e31609eb4d4e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seyahat kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Seyahat Ürünü 1",
                            Price = 2024m,
                            Sold = 4,
                            Stock = 176
                        },
                        new
                        {
                            Id = new Guid("2bc88856-e96b-4e19-9622-65fc0d6f84c0"),
                            CategoryId = new Guid("019f08bc-1283-75a5-a94f-e31609eb4d4e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seyahat kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Seyahat Ürünü 2",
                            Price = 2161m,
                            Sold = 11,
                            Stock = 179
                        },
                        new
                        {
                            Id = new Guid("f10e41c8-556a-41e8-bbff-e52cee233c12"),
                            CategoryId = new Guid("019f08bc-1283-75a5-a94f-e31609eb4d4e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seyahat kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Seyahat Ürünü 3",
                            Price = 2298m,
                            Sold = 18,
                            Stock = 182
                        },
                        new
                        {
                            Id = new Guid("6dca607b-1701-4e74-9d6c-83d93b04e0ba"),
                            CategoryId = new Guid("019f08bc-1283-75a5-a94f-e31609eb4d4e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seyahat kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Seyahat Ürünü 4",
                            Price = 2435m,
                            Sold = 25,
                            Stock = 185
                        },
                        new
                        {
                            Id = new Guid("ea6ccb86-1a28-4500-9edb-836df99b06d8"),
                            CategoryId = new Guid("019f08bc-4ff4-799f-9b8e-3badd35c0ff5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Evcil Hayvan kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Evcil Hayvan Ürünü 1",
                            Price = 2172m,
                            Sold = 32,
                            Stock = 188
                        },
                        new
                        {
                            Id = new Guid("6781191d-f6c6-43b8-b509-f855009de671"),
                            CategoryId = new Guid("019f08bc-4ff4-799f-9b8e-3badd35c0ff5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Evcil Hayvan kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Evcil Hayvan Ürünü 2",
                            Price = 2309m,
                            Sold = 39,
                            Stock = 191
                        },
                        new
                        {
                            Id = new Guid("71286aea-213f-43d5-bb2e-28dde23c4749"),
                            CategoryId = new Guid("019f08bc-4ff4-799f-9b8e-3badd35c0ff5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Evcil Hayvan kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Evcil Hayvan Ürünü 3",
                            Price = 2446m,
                            Sold = 46,
                            Stock = 194
                        },
                        new
                        {
                            Id = new Guid("18623cfa-7b1b-4dbc-be13-aa52762215af"),
                            CategoryId = new Guid("019f08bc-4ff4-799f-9b8e-3badd35c0ff5"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Evcil Hayvan kategorisi örnek ürün 4",
                            IsActive = true,
                            Name = "Evcil Hayvan Ürünü 4",
                            Price = 2583m,
                            Sold = 53,
                            Stock = 197
                        },
                        new
                        {
                            Id = new Guid("3057dc36-24a1-40f1-a468-69cb6dac3ac9"),
                            CategoryId = new Guid("019f08bc-81c0-783c-bfd7-eef39eda9c5a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kozmetik kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Kozmetik Ürünü 1",
                            Price = 2320m,
                            Sold = 60,
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("0f256e5c-b710-413d-9545-8153d9a557aa"),
                            CategoryId = new Guid("019f08bc-81c0-783c-bfd7-eef39eda9c5a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kozmetik kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Kozmetik Ürünü 2",
                            Price = 2457m,
                            Sold = 67,
                            Stock = 23
                        },
                        new
                        {
                            Id = new Guid("c86af925-583b-4290-ab68-da8f691ae5c7"),
                            CategoryId = new Guid("019f08bc-81c0-783c-bfd7-eef39eda9c5a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kozmetik kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Kozmetik Ürünü 3",
                            Price = 2594m,
                            Sold = 74,
                            Stock = 26
                        },
                        new
                        {
                            Id = new Guid("08465368-9042-4c4e-9692-0f1eaad4cf92"),
                            CategoryId = new Guid("019f08bc-bf2c-7bd0-9a50-e6c286cfed60"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Müzik kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Müzik Ürünü 1",
                            Price = 2431m,
                            Sold = 81,
                            Stock = 29
                        },
                        new
                        {
                            Id = new Guid("afa18abd-aa00-471a-96eb-f3a4fad0a3f9"),
                            CategoryId = new Guid("019f08bc-bf2c-7bd0-9a50-e6c286cfed60"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Müzik kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Müzik Ürünü 2",
                            Price = 2568m,
                            Sold = 88,
                            Stock = 32
                        },
                        new
                        {
                            Id = new Guid("5d6c926e-9585-40ff-b1ca-0cb0b37c84c5"),
                            CategoryId = new Guid("019f08bc-bf2c-7bd0-9a50-e6c286cfed60"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Müzik kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Müzik Ürünü 3",
                            Price = 2705m,
                            Sold = 5,
                            Stock = 35
                        },
                        new
                        {
                            Id = new Guid("d0e5cee4-05ab-4922-b8b8-a1418dea1a47"),
                            CategoryId = new Guid("019f08bc-e16d-7a9b-8d2d-3338247ad7c3"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Futbol kategorisi örnek ürün 1",
                            IsActive = true,
                            Name = "Futbol Ürünü 1",
                            Price = 2542m,
                            Sold = 12,
                            Stock = 38
                        },
                        new
                        {
                            Id = new Guid("bc6103fa-46f0-4e08-95b8-0f8d3b156cde"),
                            CategoryId = new Guid("019f08bc-e16d-7a9b-8d2d-3338247ad7c3"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Futbol kategorisi örnek ürün 2",
                            IsActive = true,
                            Name = "Futbol Ürünü 2",
                            Price = 2679m,
                            Sold = 19,
                            Stock = 41
                        },
                        new
                        {
                            Id = new Guid("3910a585-41e0-46ba-98ca-468b8d2c9a27"),
                            CategoryId = new Guid("019f08bc-e16d-7a9b-8d2d-3338247ad7c3"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Futbol kategorisi örnek ürün 3",
                            IsActive = true,
                            Name = "Futbol Ürünü 3",
                            Price = 2816m,
                            Sold = 26,
                            Stock = 44
                        });
                });

            modelBuilder.Entity("CartFlow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CartFlow.Models.Cart", b =>
                {
                    b.HasOne("CartFlow.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CartFlow.Models.CartItem", b =>
                {
                    b.HasOne("CartFlow.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartFlow.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CartFlow.Models.Coupon", b =>
                {
                    b.HasOne("CartFlow.Models.Cart", "Cart")
                        .WithOne("Coupon")
                        .HasForeignKey("CartFlow.Models.Coupon", "CartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("CartFlow.Models.Product", b =>
                {
                    b.HasOne("CartFlow.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CartFlow.Models.Discount", "Discount")
                        .WithMany("Products")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CartFlow.Models.User", null)
                        .WithMany("Products")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("CartFlow.Models.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("CartFlow.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CartFlow.Models.Discount", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CartFlow.Models.Product", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CartFlow.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
